#docker-compose.yml
version: '3'
    
services:

  db:
    restart: always
    image: timescale/timescaledb:latest-pg12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"